### ISSUE TITLE
Running `mux init` twice doesn't update the credentials

### ISSUE THREAD

**Issue by heff** [muxinc/cli#4]
I'm working with two different orgs and needing to switch the token credentials. I ran `mux init` again and everything appeared to work, but then when I uploaded a new asset, it uploaded it to the previous account, not the one I just initialized.

**Comment by mmcc** [comment]
Just tried to reproduce this and can't seem to. Can someone else see if this is still the case?

**Comment by mmcc** [comment]
Closing this because I can't repro, but feel free to open it if you run into it again!
